### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by alanpearce** [jedahan/zr#10]
I'm trying to package this for Nix, and when I went to add the metadata, I couldn't find a license.
Could you specify one and record it somewhere? It looks like clap is using MIT, perhaps that would be a good choice.

You might also want to check with @SX91 about their contributions, but IANAL.

**Comment by jedahan** [comment]
I was just going to make an issue for this, seeing your nix package I didn't want you to be in an ambiguous spot.

Though I like MIT (and actually prefer ISCL, which is a simplified version of MIT), I think for a package this specific and small GPL is appropriate.

It is much easier for me to go from ISC to GPL, so for the sake of expediency, I will add the ISCL, and ask:

@alanpearce @SX91 do either of you have strong opposition to GPL licensing this?

**Comment by jedahan** [comment]
(I am auditing the libraries I use right now for interoperability)

**Comment by jedahan** [comment]
clap is MIT
libgit2 is GPL-2 with linking exception (so should be MIT compat)

**Comment by jedahan** [comment]
I've narrowed it down to two options, vote by responding with the appropriate reaction
* [Mozilla Public License v2](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)) ❤️ 
  * +GPL Compatible
  * +Widely used and understood
  * -Permits patent claims
* [Open Software License v3](https://tldrlegal.com/license/open-software-licence-3.0#summary) 🎉 
  * +Simpler and shorter
  * +Denies patent claims
  * -Untested in courts
  * -GPL Incompatible

**Comment by jedahan** [comment]
We are now MPL-2.0 :)
