### ISSUE TITLE
Silent failure when ZR_HOME/plugins doesn't exist

### ISSUE THREAD

**Issue by alanpearce** [jedahan/zr#11]
Using 0.4.8

When using `zr load`, I don't see any messages. Nothing happens.
When using `zr add`, I saw some IO errors, which pointed me in the right direction.

**Comment by jedahan** [comment]
weird, it should create that directory

**Comment by alanpearce** [comment]
I wonder if it has anything to do with me having already created the .zr directory. I'm never sure whether these tools are going to create everything or not...

**Comment by jedahan** [comment]
In an ideal world it would create if not found, and  i can make that explicit maybe in the readme under a 'quick start' or 'getting started' section

**Comment by jedahan** [comment]
Should be fixed in jedahan/zr@0.6.1

**Comment by jedahan** [comment]
Lemme know if its fixed in 0.6.1

**Comment by jedahan** [comment]
Reopen if you see this isn't fixed (I haven't tested it yet but wanted to push out asap)

**Comment by alanpearce** [comment]
Sorry, I couldn't test it yet. I can't build it on Nix because the required version of clippy isn't yet available. I don't know how the language-packaging stuff works in nix, so I'll wait a few days and see if it gets updated on its own…
