### ISSUE TITLE
Repo/file argument detection issues

### ISSUE THREAD

**Issue by alanpearce** [jedahan/zr#12]
`zr` thinks that [unixorn/tumult.plugin.zsh](https://github.com/unixorn/tumult.plugin.zsh) is a file, not a repo. 
Conversely, it tries to clone `zsh/_ghq` when I want to load [`motemen/ghq zsh/_ghq`](https://github.com/motemen/ghq/blob/master/zsh/_ghq)

Perhaps zr should use a scheme like [zplug's](https://github.com/zplug/zplug#usage)? That would allow flexibility in adding keyword arguments in the future.

**Comment by jedahan** [comment]
hmm I see, so I wonder if I can detect zsh ` \`, or if it gets passed as a single long space separated file.

As a temporary solution, how bad would it be for the format to be `author/name/path/to/file.zsh`?

**Comment by alanpearce** [comment]
I think the temporary solution would work quite well, one could even use substring expansion: author/repo{,/path/to/file} as a shorthand.

Backslash would also probably work (split the string on the first space), but seems a bit ugly...

**Comment by jedahan** [comment]
Pushed 0.6.0, as a breaking change, which uses the new format. Really appreciate your bugreporting and testing @alanpearce !
