### ISSUE TITLE
Prompt is improperly quoted

### ISSUE THREAD

**Issue by arpd** [jedahan/zr#18]
In the function `prompt_filthy_setup`, the prompt is configured as follows:

```
  PROMPT='$(prompt_filthy_prompt_char) '

  RPROMPT='$(prompt_filthy_rprompt)'
```
Using `''` means that whatever's inside them won't be subject to interpolation:

```
~
❯ echo "$TERM"
xterm-256color

~
❯ echo '$TERM'
$TERM
```

**Comment by jedahan** [comment]
I don't think this has to do with zr
