### ISSUE TITLE
-h should default to --help instead of --home

### ISSUE THREAD

**Issue by I60R** [jedahan/zr#23]
I've found it a bit surprising that `zr -h` prints error message instead of help. 

Could you fix it? 

It seems that just removing `-h` from `clap_app!` would be enough

**Comment by jedahan** [comment]
Good idea. What would you recommend for choosing a directory for cloning? `-d`, `—directory` or `-z`,`—zr-home` or something else?

**Comment by I60R** [comment]
IMO, just keeping current `--home` flag would be the most reasonable option. 

I don't think that it would be used frequently, so I don't see any need in shortcuts like `-h`, `-d`, etc.
