### ISSUE TITLE
update crates.io

### ISSUE THREAD

**Issue by ralsei** [jedahan/zr#32]
version on crates.io is still 0.7.2, latest version is 0.9.0, behavior between the two changed significantly

**Comment by tekumara** [comment]
Would it also be possible to add a darwin binary for 0.9.0? 🙏 This will make it easy to install for folks without rust. Thanks!

**Comment by jedahan** [comment]
So there is one major change to how 0.9.0, and I'd like @ralsei and @tekumara to weigh in on how user-hostile it might be.

Before there was `zr update`, now, there is only one command: `zr [repo/identifier]...`. The biggest benefit of this, is that `zr` is a pure function i.e. no state is kept anywhere. The downside is if you want to update, you need to write your own function to handle it. For example, I have 

```
up::zr() { zr $(rg '^# (.*)' -r '$1' ~/.config/zr.zsh | tr '\n' ' ') > ~/.config/zr.zsh }
```

**Comment by jedahan** [comment]
I'm open to suggestions on how to handle reading the file, maybe with an environment variable

**Comment by tekumara** [comment]
I'm a new user so can easily adopt. I personally really like the functional style.

I also like being able to direct the output of `zr` to a location of my own choosing, eg:  `~/.config/` is more a Linux convention. On macOS I would probably put this elsewhere.

**Comment by tekumara** [comment]
There is still state on disk under `~/.zr/` right? So if zr recorded the full repo path in the directory name, then a `zr update` command could do an update based on the directory names in `~/.zr/`. I think this is how antibody does it.

**Comment by jedahan** [comment]
Hmm, so we have a few options.

* add a flag `--update` that recursively walks the cache directory and `git pull` for anything there
* add a flag `--update` that would `git pull` for any repo passed in as a param
* add `export ZR_ZSH=${0}` to the generated init, and have `zr update` use that

I don't like polluting the environment, but I think the third one is actually kinda nice

**Comment by jedahan** [comment]
https://crates.io/crates/zr/1.0.0 ! thanks everyone!
please submit bugreports and ideas!
