### ISSUE TITLE
Don't add to PATH

### ISSUE THREAD

**Issue by tekumara** [jedahan/zr#34]
zr adds the plugin's directory to PATH if there are executable files inside (on *nix)

eg:
```
PATH=/Users/tekumara/Library/Caches/zr/agkozak/zsh-z:$PATH
```
However many (most?) plugins don't need this, they just need to be sourced.
So my PATH ends up unnecessarily long.

Some plugin managers modify PATH (eg: antigen) but other's don't (eg: zgen, antibody, zplug).

Would it be possible to change zr to not modify PATH, or make this an option? 

Thankyou for considering this! 🙏

**Comment by jedahan** [comment]
So `zr` should only add a directory to your path if it contains executable files. I am open to tighter heuristics than whats here https://github.com/jedahan/zr/blob/main/src/plugin.rs#L143-L163

**Comment by jedahan** [comment]
A workaround for now could be something like `zr my/plugins blah/yo | grep -v '^PATH' > myconfig.zsh`

**Comment by jedahan** [comment]
Let me know if you have suggestions, or if I should keep this open.
