### ISSUE TITLE
Failed to source robbyrussell/oh-my-zsh/lib/completion.zsh

### ISSUE THREAD

**Issue by foray1010** [jedahan/zr#35]
I am using version 1.0.0 on macos 10.15.5

when trying to `zr robbyrussell/oh-my-zsh/lib/completion.zsh`, I received this error

```
cloning https://github.com/robbyrussell/oh-my-zsh/lib/completion.zsh into "/Users/me/Library/Caches/zr/robbyrussell/oh-my-zsh/lib/completion.zsh"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 34, message: "unexpected http status code: 404" }', /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/zr-1.0.0/src/plugin.rs:22:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It works on previous version

**Comment by jedahan** [comment]
try putting `.git` after oh-my-zsh, for example, `zr robbyrussell/oh-my-zsh.git/lib/completion.zsh`

We now use `.git` as a delimiter, so that we can support non-github sources.

**Comment by foray1010** [comment]
thank you! I didn't notice the delimiter changes!
