### ISSUE TITLE
Last release tarball (1.0.2) can't be compiled against openssl 3.0

### ISSUE THREAD

**Issue by TimB87** [jedahan/zr#38]
Version 1.0.2 can currently not be built against openssl 3.0, a lot of major distributions should be affected by this problem as openssl is widely in use by now.

The problem is that `Cargo.lock` defines a dependency on openssl-sys version  = "0.9.58", which will only compile with openssl 1.1.1 (and possibly older).

There is two options to solve this problem:
 - Running `cargo update` will update all dependency versions, which will also update `openssl-sys`  (currently to version = "0.9.80"), which will unbreak the build and work
 - Installing openssl 1.1.1 "on the sideline" (e.g. to /opt) and build this project with `PKG_CONFIG_PATH=/opt/openssl-1.1.1/pkgconfig:/usr/lib/pkgconfig cargo build --release`

#37 was merged in the meantime which updated all dependencies, including openssl-sys. So building from main will also work fine.

**Comment by jedahan** [comment]
Thank you for explaining - I am working on getting a little bit of automatic ci/cd, the next release should be up shortly.

**Comment by jedahan** [comment]
newest release should be up https://github.com/jedahan/zr/releases/tag/1.1.0

**Comment by jedahan** [comment]
Also on crates https://crates.io/crates/zr/1.1.0 - if this works for you, feel free to close this issue

**Comment by TimB87** [comment]
Works perfectly fine for me, thanks @jedahan! :confetti_ball:
