### ISSUE TITLE
feature request: support submodules when cloning plugins

### ISSUE THREAD

**Issue by olets** [jedahan/zr#43]
Would be nice if zr used `git clone --recurse-submodules` to clone plugins.

I don't have enough Rust to contribute a change, but maybe it's just a matter of changing

https://github.com/jedahan/zr/blob/34ec012e2d1a5fb170248e378ac669a31d9f978f/src/plugin.rs#L22

to

```diff
- git2::Repository::clone(source.as_str(), path).unwrap(); 
+ git2::Repository::clone_recurse(source.as_str(), path).unwrap(); 
```

Docs: https://docs.rs/git2/latest/git2/struct.Repository.html#method.clone_recurse (the `--recurse` mentioned in those docs is a deprecated alias of `--recurse-submodules`)

**Comment by jedahan** [comment]
Thanks for the suggestion. Made a new version, try it out.

**Comment by olets** [comment]
Sweet!

Looks like the new version isn't published to crates yet.

**Comment by olets** [comment]
It's there now.

Works! Thank you
