### ISSUE TITLE
Allow full urls for load

### ISSUE THREAD

**Issue by jedahan** [jedahan/zr#8]
It would be best to allow **https://**, **git://** full urls for plugins

**Comment by alanpearce** [comment]
Would you consider using a directory structure like [ghq's](https://github.com/motemen/ghq#directory-structures) for this? I think it would make a lot of sense.

**Comment by jedahan** [comment]
At first glance that directory structure seems nice, though there are a few potential problems I can imagine for zr.

The first is namespace collision - we could potentially have multiple `domainA/my/plugin` and `domainB/my/plugin`

Second is coming up with a kind of special dummy domain name for local directories - maybe its just the current hostname? In which case what would the `zr load` line look like, if you were to clone from another directory on your local machine?

I'll sleep on it and see if I can come up with acceptable solutions to these, and what benefits that structure provides. If you have any ideas that would be awesome!

**Comment by alanpearce** [comment]
I don't think there would be a problem with namespace collision as long as there's no priority list of sites for resolution (i.e. what's described in #7). `ghq` will clone only from GitHub if no domain name is provided. Everything else should be of the form `bitbucket.org/my/project` or similar.

For local plugins, one option is a special name (zplugin uses `_local`). Another might be to not store them inside `zr`'s plugin area at all: `ghq` has a zsh completion file shipped with it and at least for me, it would make sense just to reference its zsh sources instead of copying.

**Comment by jedahan** [comment]
I am pretty ok with adding domainname to the plugin identifier. For now I will add https and git protocol support, and maybe figure out file:// protocol support later.

**Comment by jedahan** [comment]
Some id resolution rules:

If there is no domain, assume github.com
If there is no protocol, assume https
If git protocol and no user, assume git user

`frmendes/geometry` => `github.com/frmendes/geometry` => `https://github.com/frmendes/geometry`
`gitlab.com/veggiemonk/almostontop` => `https://gitlab.com/veggiemonk/almostontop`
`gitlab.com:veggiemonk/almostontop` => `git@gitlab.com:veggiemonk/almostontop`

**Comment by jedahan** [comment]
For in memory and on disk, the identifier for a given plugin is `domain/author/repo`

Should `zr list` output that, or the first remote uri?

**Comment by alanpearce** [comment]
The ID resolution makes a lot of sense. I think `ghq get` works the same way and I was never surprised by it.

I think domain/author/repo makes more sense. It gives enough information to find the files.  `ghq list` also shows `domain/path` and it looks nice, so I think it would make sense to follow that.

**Comment by jedahan** [comment]
Going to add `branch` in addition to domain, and make that default to 'master' unless there is a better way to get a default branch

**Comment by druzn3k** [comment]
I want to try with this issue, is still available?

**Comment by jedahan** [comment]
Go for it @druzn3k ! Just a heads up, I think you will need to use nightly rust until 1.30 comes out then it will work back on stable. Also ask as many questions as needed because the code isn't the best

**Comment by druzn3k** [comment]
Thank you @jedahan :+1:

**Comment by druzn3k** [comment]
A small update: I'm familiarizing with the codebase. Would you eventually mind a little refactoring? In an attempt to learn rust I want to try to make the code more specific in the handling of errors, avoiding the unwrapping panics.

**Comment by jedahan** [comment]
@druzn3k certainly I am welcome to refactoring, though I would ask to separate out refactoring commits from adding/changing functionality so its easier to review and merge

**Comment by jedahan** [comment]
No worries, thanks for taking a crack at it. Let me know if there is a specific thing that was most painful and I'll make sure to write more comments or make sure to share it with the rust teams on irc and reddit.
I really struggled for years with rust and just barely can make it do a thing :)

**Comment by jedahan** [comment]
Fixed in d5dab3e24d780e75de2fe4991d67ef5bd7ddc0d6

If you wanna see how I tackled it @druzn3k , the main thing was changing the idea of an identifier from `author/name` to simply a Url, and implementing the `From<String>` trait for `author/name` that resolves to `https://github.com/author/name`.
